# Generated by Django 4.2.3 on 2023-08-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_advertisement_image_alter_advertisement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
    ]
